apps/contents/urls.py
from django.contrib import admin
from django.urls import path

from apps.contents import views

app_name = 'contents'

urlpatterns = [
    # 注册
    path('', views.IndexView.as_view(), name='index'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('', include("contents.urls")),
    path('', include("verifications.urls"))

    # path('',include(""))
]

templates/A.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>。。。</title>
</head>
<body>
    <p>没做这个，正在完善，写个连接玩儿的。。。。</p>
    <p>以表歉意，附上一张西南打针王的图片</p>
<img src="/static/images/southwest.jpg" width="450" height="500" >
</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>LG商城-登录</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/2.png' %}"></a>
	</div>
	<div class="login_form_bg" id="app">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">商品美 · 种类多 · 欢迎光临</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<a href="javascript:;" class="cur">账户登录</a>
				</div>
				<div class="form_con">
					<div class="form_input cur">
						<form method="post" class="login-form" @submit="on_submit" v-cloak>
                            {% csrf_token %}
							<input type="text" v-model="username" @blur="check_username" name="username" class="name_input" placeholder="请输入用户名">
							<div v-show="error_username" class="user_error">请输入正确的用户名</div>
							<input type="password" v-model="password" @blur="check_password" name="password" class="pass_input" placeholder="请输入密码">
							<div v-show="error_password" class="pwd_error">密码最少8位，最长20位</div>
							<div class="more_input clearfix">
								<input type="checkbox" v-model="remembered" name="remembered">
								<label>记住登录</label>
							</div>
							<div class="pwd_error">
								{% if forms_errors %}
									{% for key,error in forms_errors.items %}
										{{ error }}
									{% endfor %}
								{% endif %}

								{% if account_errmsg %}
									{{ account_errmsg }}
								{% endif %}

							</div>
							<input type="submit" value="登 录" class="input_submit">
						</form>
					</div>
				</div>
				<div class="third_party">
					<a @click="qq_login" class="qq_login" href="/users/QQAndWeixin/">QQ</a>
					<a href="/users/QQAndWeixin/" class="weixin_login">微信</a>
					<a href="/users/register/" class="register_btn">立即注册</a>
				</div>
			</div>
		</div>
	</div>
	<div class="footer no-mp">
		 <div class="foot_link">
            <a href="/users/QQAndWeixin/">关于我们</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">联系我们</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">招聘人才</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
	</div>
    <script type="text/javascript" src="{% static 'js/common.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/login.js' %}"></script>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>LG商城-注册</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<div id="app">
	<div class="register_con">
		<div class="l_con fl">
			<a href="index.html" class="reg_logo"><img src="{% static 'images/1.png' %}"></a>
			<div class="reg_slogan">商品美 · 种类多 · 欢迎光临</div>
			<div class="reg_banner"></div>
		</div>
		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="/users/login/">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post" class="register_form" @submit="on_submit" v-cloak>
					{% csrf_token %}
					<ul>
						<li>
							<label>用户名:</label>
							<input type="text" name="username" v-model="username" @blur="check_username" id="user_name">
							<!--v-show 为false 元素会隐藏-->
							<span class="error_tip" v-show="error_name">[[ error_name_message ]]</span>
						</li>					
						<li>
							<label>密码:</label>
							<input type="password" name="password" v-model="password" @blur="check_password" id="pwd">
							<span class="error_tip" v-show="error_password">请输入8-20位的密码</span>
						</li>
						<li>
							<label>确认密码:</label>
							<input type="password" name="password2"  v-model="password2" @blur="check_password2" id="cpwd">
							<span class="error_tip" v-show="error_password2">两次输入的密码不一致</span>
						</li>
						<li>
							<label>邮箱:</label>
							<input type="text" name="email" v-model="email" @blur="check_email" id="email">
							<span class="error_tip" v-show="error_email">[[error_email_message]]</span>
						</li>
						<li>
                            <label>邮箱验证码:</label>
                            <input type="text" v-model="email_code" @blur="check_email_code" name="email_code" id="msg_code"
                                   class="msg_input">
                            <a @click="send_email_code" class="get_msg_code">[[ email_code_tip ]]</a>
                            <span class="error_tip" v-show="error_email_code">[[ error_email_code_message ]]</span>
                                {% if email_code_errmsg %}
                                <span class="error_tip">
                                    {{ email_code_errmsg }}
                                </span>
                                {% endif %}

                        </li>
						<li class="agreement">
							<input type="checkbox" name="allow" v-model="allow" @change="check_allow" id="allow">
							<label>同意”LG商城用户使用协议“</label>
							<span class="error_tip" v-show="error_allow">请勾选用户协议</span>
							<span class="error_tip">
								{% if register_errmsg %}
									{{ register_errmsg }}
								{% endif %}
							</span>
						</li>
						<li class="reg_sub">
							<input type="submit" value="注 册">
						</li>
					</ul>				
				</form>
			</div>
		</div>
	</div>
	<div class="footer no-mp">
		 <div class="foot_link">
            <a href="/users/QQAndWeixin/">关于我们</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">联系我们</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">招聘人才</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
	</div>
</div>
</body>
<script src="{% static 'js/vue-2.5.16.js' %}"></script>
<script src="{% static 'js/axios-0.18.0.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>
<script src="{% static 'js/register.js' %}"></script>
</html>

templates/user_center_info.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>美多商城-用户中心</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <script type="text/javascript" src="{% static 'js/vue-2.5.16.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/axios-0.18.0.min.js' %}"></script>
    <style>
        .user_info_list {
            font-family: Arial, sans-serif; /* 设置字体 */
            list-style-type: none; /* 去除列表项的默认样式 */
            padding-left: 0; /* 去除列表左侧的默认内边距 */
        }

        .user_info_list p {
            margin: 5px 0; /* 设置段落的上下间距 */
            font-size: 15px;
        }

        .user_info_list span {
            font-weight: bold; /* 设置span元素的字体加粗 */
        }

        .info_edit_link p {
            margin: 0;
        }
    </style>
</head>
<body>
<div id="app">
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">欢迎来到LG商城!</div>
            <div class="fr">

                {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        欢迎您：<em>{{ user.username }}</em>
                        <span>|</span>
                        <a href="/users/logout/">退出</a>

                    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="/users/login/">登录</a>
                        <span>|</span>
                        <a href="/users/register/">注册</a>
                    </div>
                {% endif %}
                {#               <div class="login_btn fl" v-if="username">#}
                {#                    欢迎您：<em>[[ username ]]</em>#}
                {#                    <span>|</span>#}
                {#                    <a href="/users/logout/">退出</a>#}
                {#                   #}
                {#                </div>#}
                {#				<div v-else class="login_btn fl">#}
                {#					<a href="/users/login/">登录</a>#}
                {#					<span>|</span>#}
                {#					<a href="/users/register/">注册</a>#}
                {#				</div>#}

                <div class="user_link fl">
                    <span>|</span>
                    <a href="/users/user_info/">用户中心</a>
                    <span>|</span>
                    <a href="/users/QQAndWeixin/">我的购物车</a>
                    <span>|</span>
                    <a href="/users/QQAndWeixin/">我的订单</a>
                </div>
            </div>
        </div>
    </div>
    <div class="search_bar clearfix">
        <a href="{% url 'contents:index' %}" class="logo fl"><img src="{% static 'images/1.png' %}"></a>
        <div class="search_wrap fl">
            <form method="get" action="/search/" class="search_con">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
            <ul class="search_suggest fl">
                <li><a href="#">索尼微单</a></li>
                <li><a href="#">优惠15元</a></li>
                <li><a href="#">美妆个护</a></li>
                <li><a href="#">买2免1</a></li>
            </ul>
        </div>
    </div>
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="/users/user_info/" class="active">· 个人信息</a></li>
                <li><a href="">· 收货地址</a></li>
                <li><a href="/users/QQAndWeixin/">· 全部订单</a></li>

            </ul>
        </div>
        <div class="right_content clearfix" v-cloak>
            <div class="info_con clearfix">
                <h3 class="common_title2">基本信息</h3>

                <ul class="user_info_list ">
                    <p><span>用户名：</span>{{ username }}</p>
                    <p><span>真实姓名：</span>{{ name }}</p>
                    <p><span>性别：</span>{{ gender }}</p>
                    <p><span>邮箱：</span>{{ email }}</p>
                    <p><span>地址：</span>{{ address }}</p>
                </ul>
            </div>
            <div class="info_edit_link">如果您发现以上信息有误，请立即 <a href="/users/user_edit/{{ id }}">更改信息</a>。（缺少异常输入和报错处理，后续修改，表格内容全部填写完整）
            </div>
            <h3 class="common_title2">最近浏览</h3>
            <div class="has_view_list" v-cloak>
                <ul class="goods_type_list clearfix">
                    <li v-for="sku in histories">
                        <a :href="sku.url"><img :src="sku.default_image_url"></a>
                        <h4><a :href="sku.url">[[ sku.name ]]</a></h4>
                        <div class="operate">
                            <span class="price">￥[[ sku.price ]]</span>
                            <span class="unit">台</span>
                            <a href="javascript:;" class="add_goods" title="加入购物车"></a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="foot_link">
            <a href="/users/QQAndWeixin/">关于我们</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">联系我们</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">招聘人才</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</div>
<script type="text/javascript">
    let username = "{{ username }}";
    let mobile = "{{ mobile }}";
    let email = "{{ email }}";
    let email_active = "{{ email_active }}";
</script>
<script type="text/javascript" src="{% static 'js/common.js' %}"></script>
<script type="text/javascript" src="{% static 'js/user_center_info.js' %}"></script>
</body>
</html>

templates/user_edit.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>LG商城-注册</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
<div id="app">
    <div class="register_con">
        <div class="l_con fl">
            <a href="index.html" class="reg_logo"><img src="{% static 'images/1.png' %}"></a>
            <div class="reg_slogan">商品美 · 种类多 · 欢迎光临</div>
            <div class="reg_banner"></div>
        </div>
        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>用户信息修改</h1>

            </div>
            <div class="reg_form clearfix">
                <form method="post">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="username" v-model="username" @blur="check_username" id="user_name">
                            <!--v-show 为false 元素会隐藏-->
                            <span class="error_tip" v-show="error_name">[[ error_name_message ]]</span>
                        </li>
                        <li>
                            <label>密码:</label>
                            <input type="password" name="password" v-model="password" @blur="check_password" id="pwd">
                            <span class="error_tip" v-show="error_password">请输入8-20位的密码</span>
                        </li>
                        <li>
                            <label>确认密码:</label>
                            <input type="password" name="password2" v-model="password2" @blur="check_password2"
                                   id="cpwd">
                            <span class="error_tip" v-show="error_password2">两次输入的密码不一致</span>
                        </li>

                        <li>
                            <label>真正姓名:</label>
                            <input type="text" name="name" id="name">
                            
                        </li>
                        <li>
                            <label>手机号:</label>
                            <input type="text" name="mobile" id="pwd">
                            
                        </li>

                        <li>
                            <label>住址:</label>
                            <input type="text" name="address" id="address">
                           
                        </li>
                        <li>
                            <label for="gender">性别:</label>
                            <select name="gender" id="gender">
                                <option value="1">男</option>
                                <option value="2">女</option>
                                
                            </select>
                        </li>
                        <li class="reg_sub">
                            <input type="submit" value="保 存">
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </div>
    <div class="footer no-mp">
         <div class="foot_link">
            <a href="/users/QQAndWeixin/">关于我们</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">联系我们</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">招聘人才</a>
            <span>|</span>
            <a href="/users/QQAndWeixin/">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京美多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</div>
</body>
<script src="{% static 'js/vue-2.5.16.js' %}"></script>
<script src="{% static 'js/axios-0.18.0.min.js' %}"></script>
<script src="{% static 'js/common.js' %}"></script>
<script src="{% static 'js/register.js' %}"></script>
</html>